#!/bin/bash
## Generate SettingsData.generated.h from preprocessor-extracted settings.
##
## Usage: gen_settings_data.sh <compiler> <source_dir> <binary_dir>
##
## The script:
## 1. Preprocesses gen_settings_extract.cpp to get TYPE/NAME/DEFAULT for each setting
## 2. Groups settings by type into arrays
## 3. Emits a Data struct, SettingOffset constants, and a default-value constructor

set -euo pipefail

CXX="${1:?Usage: gen_settings_data.sh <compiler> <source_dir> <binary_dir>}"
SOURCE_DIR="${2:?}"
BINARY_DIR="${3:?}"

OUTPUT="${BINARY_DIR}/SettingsData.generated.h"

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

## Step 1: Preprocess to extract settings
## The preprocessor may emit errors for unrelated includes (config.h, etc.)
## but still produces correct output for the settings macros on stdout.
"$CXX" -E -P \
    -I "${SOURCE_DIR}" \
    -I "${SOURCE_DIR}/Core" \
    -I "${SOURCE_DIR}/../base" \
    "${SOURCE_DIR}/Core/gen_settings_extract.cpp" 2>/dev/null \
    | tr '\n' ' ' \
    | grep -oP '__SETTING__.*?__END__' \
    | sed 's/__SETTING__\s*//; s/\s*__END__//; s/\s*__SEP__\s*/\t/g' \
    > "$TMPDIR/settings.txt" || true

TOTAL=$(wc -l < "$TMPDIR/settings.txt")
if [ "$TOTAL" -eq 0 ]; then
    echo "ERROR: No settings extracted" >&2
    exit 1
fi

## Step 2: Group by type
declare -a TYPE_ORDER=()
declare -A TYPE_SEEN=()

while IFS=$'\t' read -r TYPE NAME DEFAULT; do
    if [[ -z "${TYPE_SEEN[$TYPE]+x}" ]]; then
        TYPE_ORDER+=("$TYPE")
        TYPE_SEEN[$TYPE]=1
    fi
    printf '%s\t%s\n' "$NAME" "$DEFAULT" >> "$TMPDIR/$TYPE.txt"
done < "$TMPDIR/settings.txt"

## Step 3: Generate output
{
cat <<'HEADER'
#pragma once
/// Auto-generated by gen_settings_data.sh — do not edit.
/// This file is included from within namespace DB { } scope in Settings.cpp.

#include <cstddef>
#include <Core/SettingIndex.h>

HEADER

## Data struct with typed arrays
echo "struct SettingsData"
echo "{"
for TYPE in "${TYPE_ORDER[@]}"; do
    COUNT=$(wc -l < "$TMPDIR/$TYPE.txt")
    echo "    SettingField${TYPE} ${TYPE}_[${COUNT}];"
done
echo ""
echo "    SettingsData();"
echo "};"
echo ""

## SettingOffset namespace with constexpr offsets
echo "namespace SettingOffset"
echo "{"
for TYPE in "${TYPE_ORDER[@]}"; do
    IDX=0
    while IFS=$'\t' read -r NAME _DEFAULT; do
        echo "inline constexpr SettingIndex<SettingField${TYPE}> ${NAME}{offsetof(SettingsData, ${TYPE}_) + ${IDX} * sizeof(SettingField${TYPE})};"
        IDX=$((IDX + 1))
    done < "$TMPDIR/$TYPE.txt"
done
echo "}"
echo ""

## Constructor with default values
echo "inline SettingsData::SettingsData()"
echo "{"
for TYPE in "${TYPE_ORDER[@]}"; do
    IDX=0
    while IFS=$'\t' read -r NAME DEFAULT; do
        echo "    ${TYPE}_[${IDX}] = SettingField${TYPE}(${DEFAULT});"
        IDX=$((IDX + 1))
    done < "$TMPDIR/$TYPE.txt"
done
echo "}"

} > "$OUTPUT"

echo "Generated $OUTPUT ($TOTAL settings)" >&2
